#!/usr/bin/env python3

from pygame.locals import *

# graphics
FPS = 60
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
SCREEN_FULLSCREEN = False

# input
INPUT_CAMERA_CCW = K_PAGEUP
INPUT_CAMERA_CW = K_PAGEDOWN
INPUT_CAMERA_LEFT = K_LEFT
INPUT_CAMERA_RIGHT = K_RIGHT
INPUT_CAMERA_UP = K_UP
INPUT_CAMERA_DOWN = K_DOWN

INPUT_TURN_LEFT = K_a
INPUT_TURN_RIGHT = K_d
INPUT_MOVE_FRONT = K_w
INPUT_MOVE_BACK = K_s
